### ISSUE TITLE
Не получается собрать исполняемый файл на linux.

### ISSUE THREAD

**Issue by agent-atlas** [TechUnRestricted/Kufar-Telegram-Notifier#1]
Выдает такую ошибку

helperfunctions.cpp:17:49: error: no matching function for call to ‘find(std::vector<int>::const_iterator, std::vector<int>::const_iterator, const int&)’
     if (find(vector.begin(), vector.end(), value) != vector.end()){

**Comment by agent-atlas** [comment]
не хватало библиотеки

**Comment by TechUnRestricted** [comment]
> не хватало библиотеки

Вы подключили библиотеку
`#include <algorithm>` ?
