### ISSUE TITLE
 cached-data.json не сохраняет ид

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#11]
Содержит только []
Не сохраняет ид

**Comment by TechUnRestricted** [comment]
ID сохранялись, но только при получении <code>SIGINT</code> сигнала по нажатию на <code>^C</code>
В <a href="https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.6">версии 2.6</a> немного изменил логику. Теперь объявления должны сохраняться по мере их поступления.

**Comment by sort84** [comment]
Не сохраняет

**Comment by sort84** [comment]
> ID сохранялись, но только при получении `SIGINT` сигнала по нажатию на `^C` В [версии 2.6](https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.6) немного изменил логику. Теперь объявления должны сохраняться по мере их поступления.

Не сохраняет
