### ISSUE TITLE
Ошибка при g++ *.cpp -o executable -std=c++17 -lcurl

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#2]
Выполняю 
`g++ *.cpp -o executable -std=c++17 -lcurl`

Получаю 

`helperfunctions.cpp: In function ‘bool vectorContains(const std::vector<int>&, const int&)’:
helperfunctions.cpp:17:49: error: no matching function for call to ‘find(std::vector<int>::const_iterator, std::vector<int>::const_iterator, const int&)’
   17 |     if (find(vector.begin(), vector.end(), value) != vector.end()){
      |                                                 ^
In file included from /usr/include/c++/10/bits/locale_facets.h:48,
                 from /usr/include/c++/10/bits/basic_ios.h:37,
                 from /usr/include/c++/10/ios:44,
                 from /usr/include/c++/10/istream:38,
                 from /usr/include/c++/10/fstream:38,
                 from helperfunctions.cpp:9:
/usr/include/c++/10/bits/streambuf_iterator.h:422:5: note: candidate: ‘template<class _CharT2> typename __gnu_cxx::__enable_if<std::__is_char<_CharT2>::__value, std::istreambuf_iterator<_CharT> >::__type std::find(std::istreambuf_iterator<_CharT>, std::istreambuf_iterator<_CharT>, const _CharT2&)’
  422 |     find(istreambuf_iterator<_CharT> __first,
      |     ^~~~
/usr/include/c++/10/bits/streambuf_iterator.h:422:5: note:   template argument deduction/substitution failed:
helperfunctions.cpp:17:49: note:   ‘__gnu_cxx::__normal_iterator<const int*, std::vector<int> >’ is not derived from ‘std::istreambuf_iterator<_CharT>’
   17 |     if (find(vector.begin(), vector.end(), value) != vector.end()){
      |                                                 ^
networking.cpp:9:10: fatal error: curl/curl.h: No such file or directory
    9 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
`

**Comment by TechUnRestricted** [comment]
Проверьте исправленный вариант:
https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.1

Но перед этим убедитесь, что curl установлен корректно:
`sudo apt-get install curl libcurl4-gnutls-dev`

**Comment by sort84** [comment]
> Проверьте исправленный вариант: https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.1

`networking.cpp:9:10: fatal error: curl/curl.h: No such file or directory
    9 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
`

**Comment by sort84** [comment]
Все отлично. Ubuntu
