### ISSUE TITLE
Добавить поиск по категориям, сортировка по времени

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#3]
Просьба добавить :
- поиск по категориям 
&cat=
- сортировка
&sort=lst.d (по времени)

**Comment by sort84** [comment]
Очень нужно. Был бы признателен за добавление, а то поиск по имени модели дает много лишнего в других категориях

**Comment by TechUnRestricted** [comment]
Постараюсь добавить в скором времени

**Comment by TechUnRestricted** [comment]
Добавлено в версии [2.4](https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.4)
