### ISSUE TITLE
Как указать поиск по всей Беларуси, без указания городов и областей?

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#4]
Как указать поиск по всей Беларуси, без указания городов и областей?

**Comment by TechUnRestricted** [comment]
Спасибо за Ваше сообщение!
Начиная с [версии 2.2](https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.2) появилась возможность указания поиска по всей Беларуси.

Для этого просто удалите из файла конфигурации следующее: `region` и `areas`
<img src="https://user-images.githubusercontent.com/83237609/181227633-2d4a2359-40c7-40f3-bb68-c4a0ae5438fa.png" width="400"/>

Таким же образом можно убрать любой ненужный Вам объект из объекта `queries`, кроме `tag`
