### ISSUE TITLE
Пишу chatid 5324902671 а в скрипте вывод - Chat ID: 1029935376

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#5]
Пишу в конфиг chatid 5324902671
а в скрипте вывод - Chat ID: 1029935376 
и не приходит оповещение в телеграм

Если писать chatid 227021753
 в скрипте вывод - Chat ID: 227021753
то все приходит

**Comment by TechUnRestricted** [comment]
Спасибо за Ваше сообщение!
Начиная с [версии 2.2](https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.2) проблема должна уйти.
