### ISSUE TITLE
 ./executable "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json" не работает

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#6]
`root@CLOUD-VPS:~/Kufar-Telegram-Notifier-2.2/Kufar Telegram Notifier# ./executable "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"
[Loading configuration]: "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
Aborted (core dumped)
`

Все пункты выполнены
kufar-configuration.json оставил по умолчанию и не изменял
Что делаю не так?

**Comment by sort84** [comment]
Причем на 2,1 все запускается.

**Comment by TechUnRestricted** [comment]
У Вас синтаксическая ошибка в JSON файле. Прикрепите содержимое файла конфигурации. С файлом по умолчанию у меня всё запускается корректно.
<details>
  <summary>macOS</summary>
<img width="682" alt="image" src="https://user-images.githubusercontent.com/83237609/181460068-3705dbeb-ec08-477d-ae8e-dbdf5a853ff5.png">
</details>
<details>
  <summary>Ubuntu</summary>
<img width="391" alt="image" src="https://user-images.githubusercontent.com/83237609/181460761-1f02b2dc-5f78-46da-8009-aa148789c4bf.png">
</details>

**Comment by sort84** [comment]
kufar-configuration.json оставил по умолчанию и не изменял
Копировал с версии 2.1

Сейчас проверю

**Comment by sort84** [comment]
` ./executable ../kufar-configuration.json `
 вот так запустился, даже не изменяя kufar-configuration.json 

А так не хочет
`./executable "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"
`

**Comment by TechUnRestricted** [comment]
Проверил работоспособность, всё отлично:
![image](https://user-images.githubusercontent.com/83237609/181465246-00a4d427-f0d5-448e-82a0-1c2c39c5598e.png)

У вас, как мне кажется, неверно указан путь к файлу конфигурации.

> А так не хочет
> `./executable "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"`

Путь к файлу у Вас начинается с root директории, минуя папку home и имя пользователя.

**Comment by sort84** [comment]
Я пробовал различные варианты пути. Не помогало.

Просьба добавить в инструкцию, а то найдутся такие же вопросы, у кого не получается

**Comment by TechUnRestricted** [comment]
> Я пробовал различные варианты пути. Не помогало.
Это всё равно значит, что Вы указали неверный путь к файлу. 

Давайте разберем ситуацию:
> root@CLOUD-VPS:~/Kufar-Telegram-Notifier-2.2/Kufar Telegram Notifier# ./executable "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"

Вы запускаете программу из пути `~/Kufar-Telegram-Notifier-2.2/Kufar Telegram Notifier`, но путь к файлу конфигурации Вы указываете следующим образом: `"/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"`.

Ваша проблема в том, что во втором случае Вы забыли символ `~`, который автоматически переводит на домашнюю директорию папки пользователя, где у Вас находится папка `Kufar-Telegram-Notifier-2.2`.

То есть по итогу должно быть так:
`./executable ~/"Kufar-Telegram-Notifier-2.2/kufar-configuration.json"`

Это поведение не заложено в коде моей программы. Это особенность UNIX систем.

**Comment by sort84** [comment]
Я указывал и тильду, и / и без, и выходил на уровень ниже, менял путь в executable
Оно не помогало
Для меня помогло запуск из папки Kufar-Telegram-Notifier-2.2/Kufar Telegram Notifie по команде

`./executable ../kufar-configuration.json`

**Comment by sort84** [comment]
Причем в 2,1 все работало 
`./executable "/Kufar-Telegram-Notifier-2.2/kufar-configuration.json"`

**Comment by TechUnRestricted** [comment]
«can't reproduce»
