### ISSUE TITLE
При повторном запуске идет сбор заново. Исключить его

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#7]
Если запустить заново, то объявление собирает повторно и отсылает в телеграм. Может сохранять в txt id объявлений и при повторном запуске проверять их в txt, и если оно там есть, не отсылать в телеграм?

**Comment by TechUnRestricted** [comment]
Исправлено в версии [2.4](https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.4)
