### ISSUE TITLE
kufar.hpp  - первый символ в слове сlothingUpTo1Year(300 строка) на кирилице и ....

### ISSUE THREAD

**Issue by sort84** [TechUnRestricted/Kufar-Telegram-Notifier#8]
kufar.hpp  - первый символ в слове сlothingUpTo1Year(300 строка) на кирилице

https://i.imgur.com/WlkbWi2.png

**Comment by TechUnRestricted** [comment]
Я случайно первым символом ввёл русскую букву.
На macOS данный проект собрался без проблем, но на Linux не проверял.

Проверьте версию <a href="https://github.com/TechUnRestricted/Kufar-Telegram-Notifier/releases/tag/2.5.1">2.5.1</a>. Ошибка должна быть исправлена.
Только перечитайте <a href="https://github.com/TechUnRestricted/Kufar-Telegram-Notifier#---------linux------">инструкцию по сборке</a>, так как она изменилась.

Спасибо за отчёт.
